// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function PokeMiner(arg1:string,arg2:number):Promise<main.SystemInfo>;

export function Start(arg1:number):Promise<void>;

export function ToggleManager(arg1:number):Promise<void>;
