// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {miners} from '../models';

export function ExportToCsv(arg1:string):Promise<void>;

export function Probe(arg1:string,arg2:string):Promise<miners.MinerInfo>;

export function ReadyListener():Promise<void>;

export function StartListeningToPorts(arg1:Array<number>):Promise<void>;
