// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializePorts(arg1) {
  return window['go']['main']['App']['InitializePorts'](arg1);
}

export function PokeMiner(arg1, arg2, arg3) {
  return window['go']['main']['App']['PokeMiner'](arg1, arg2, arg3);
}

export function StartListeningPorts(arg1) {
  return window['go']['main']['App']['StartListeningPorts'](arg1);
}
