// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InitializePorts(arg1:Array<number>):Promise<void>;

export function PokeMiner(arg1:string,arg2:string,arg3:string):Promise<main.RawSignalMessage>;

export function StartListeningPorts(arg1:Array<number>):Promise<void>;
