// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPorts() {
  return window['go']['main']['App']['LoadPorts']();
}

export function PokeMiner(arg1, arg2, arg3) {
  return window['go']['main']['App']['PokeMiner'](arg1, arg2, arg3);
}

export function Replace(arg1) {
  return window['go']['main']['App']['Replace'](arg1);
}

export function SavePorts(arg1) {
  return window['go']['main']['App']['SavePorts'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function ToggleManager(arg1) {
  return window['go']['main']['App']['ToggleManager'](arg1);
}
